[build]
  command = "npx prisma generate && next build"
  publish = ".next"
  ignore = "git diff --quiet HEAD^ HEAD ./"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps --force"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    skipBuildCache = true
    experimentalBundling = false

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[functions]
  included_files = ["prisma/**"]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", "prisma"]

[dev]
  framework = "next"
  targetPort = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 