[build]
  command = "npm install && npx prisma generate && npx prisma migrate deploy && next build"
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_FORCE_EDGE_IMAGES = "true"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  included_files = [".env"]

[secrets_scan]
  omit_paths = [
    "package-lock.json",
    ".next/**/*",
    ".netlify/**/*",
    ".netlify/edge-functions/**/*"
  ]
  omit_keys = [
    "NODE_VERSION",
    "NEXTAUTH_URL",
    "DATABASE_URL",
    "DIRECT_URL"
  ]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 